package com.example.travelapp

object Constants {
    const val EVENT_LOGIN_BUTTON_CLICK = "EVENT_LOGIN_BUTTON_CLICK"
    const val EVENT_REGISTER_BUTTON_CLICK = "EVENT_REGISTER_BUTTON_CLICK"
    const val EVENT_REGISTER_SUCCESSFUL = "EVENT_REGISTER_BUTTON_CLICK"
    const val EVENT_LOGIN_SUCCESSFUL = "EVENT_LOGIN_SUCCESSFUL"
    const val OPEN_DASHBOARD = "OPEN_DASHBOARD"
}